# Generated by Django 4.1.3 on 2022-11-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telesettings',
            old_name='tg_text',
            new_name='tg_message',
        ),
    ]
